### ISSUE TITLE
Support for Config files

### ISSUE THREAD

**Issue by 85pando** [enterpriseWifiSafeguard/EnterpriseWifiSafeguard#10]
Entities like Companies or Universities could provide config files, so that most of the settings are automatically filled in.

**Comment by petejoybaker** [comment]
Yeah, there is a rudimentary import function to do this.

**Comment by 85pando** [comment]
Yeah, right, did not sea this. Unfortunately it crashes for me, when I try to do this.

**Comment by xamor** [comment]
Oh this should not happen, can you tell me more about your system? Do you use cyanogenmod?

**Comment by xamor** [comment]
Ok i think the problem was, there was no config file on the internal SD card. I fixed this issue by checking if a config file exists or not in 7baed2971f58c6ad1f2ebea3e7ff46c10bc970d2. The config file has to be in /EnterpriseWifiSafeguard and has to be named as config.txt. I choosed this way because the android API has no own filechooser and if you want to use a filechooser you have to install a filemanager like "Dateimanager" on cyanogenmod. I expect that not all File Managers are supported by the android API so i choosed the hardcoded way. Maybe we could implement the option to set the config filename in a later version.

**Comment by 85pando** [comment]
Right, when first exporting a file (probably also copying it into the correct folder with the correct name) it will import everything except username and password (which is as it should be).

**Comment by xamor** [comment]
In the bin folder is a new apk which avoids crashing if there is no config file

**Comment by 85pando** [comment]
Import seems to not import the EAP-Method, Phase2-Method and Root Certificate.

**Comment by xamor** [comment]
Are you sure? On my system it works. I know its a bad hack how it works but it should work. If i import a configurations the spinners will be set on the position saved in the config.

**Comment by 85pando** [comment]
- Set the settings:
  
  ![before](https://cloud.githubusercontent.com/assets/1187085/9573389/39e80e3c-4fbc-11e5-8fed-7cfd7e37ef72.png)
- Leave the app and close it.
- restart app, import:
  
  ![after](https://cloud.githubusercontent.com/assets/1187085/9573390/39e86b8e-4fbc-11e5-8863-c750b0ca97cf.png)

**Comment by xamor** [comment]
This is a strange beheavior. But i think i got a solution.

**Comment by xamor** [comment]
Fixed in 3ffe9dccd557f5b9a4177f83a6132865c62f73b7

**Comment by 85pando** [comment]
Verified, works
